//
//  DocDetailModel.h
//  SmartOffice
//
//  Created by Kaka on 5/16/17.
//  Copyright © 2017 ITSOL. All rights reserved.
//

#import "SOBaseModel.h"
#import "MemberModel.h"
@interface DocDetailModel : SOBaseModel{
	
}
@property (strong, nonatomic) NSString *documentId;
@property (strong, nonatomic) NSString *title;
@property (strong, nonatomic) NSString *content;
@property (strong, nonatomic) NSString *departSentSign;
@property (strong, nonatomic) NSString *creator;
@property (strong, nonatomic) NSString *createDate;
@property (strong, nonatomic) NSString *toDate;
@property (assign, nonatomic) BOOL isArrive;
@property (strong, nonatomic) NSString *priority;
@property (assign, nonatomic) NSInteger priorityId;
@property (assign, nonatomic) NSInteger stypeId;
@property (strong, nonatomic) NSString *stype;

@property (strong, nonatomic) NSString *officeSender;
@property (strong, nonatomic) NSString *area;
@property (strong, nonatomic) NSArray<MemberModel> *listMainSigner;
@property (strong, nonatomic) NSString *promulgatingDepart;

//ForDoc
@property (strong, nonatomic) NSString *signer;

@end

//namnh-itsol [4:01 PM]
//priorityId : id độ khẩn ( 1 - bình thường; 2 - khẩn; 3 - hỏa tốc; 4 - thượng khẩn).
//
//[4:01]
//stypeId :id độ mật (2 - mật; #2 - bình thường)


//
//
//{
//	"data": {
//		"documentId": 382752,
//		"registerNumber": "12",
//		"officeSender": "dfa",
//		"code": "12/CV-dfa",
//		"title": "test gui van ban cho admin",
//		"promulgateDate": "26/07/2012 00:00:00",
//		"receiveDate": "26/07/2012 00:00:00",
//		"deadlineDate": "29/07/2012 00:00:00",
//		"isArrive": 1,
//		"priorityId": 1,
//		"priority": "Bình thường",
//		"content": "test gui van ban cho admin",
//		"stypeId": 1,
//		"stype": "Bình thường",
//		"areaId": 1,
//		"area": "Hành Chính",
//		"isLock": 1,
//		"creatorId": 74,
//		"numberOfCopy": 2,
//		"listAttachment": [
//						   {
//							   "documentId": 382752,
//							   "attachment": "/Van_ban/2012/7/26/382752/SEFOLTgwMDI4NTIyOTAwMDAtMDlDTi1ZMjAxMS1MMDAgQkg=.pdf",
//							   "name": "HAN-8002852290000-09CN-Y2011-L00 BH.pdf",
//							   "fileAttachmentId": 373056
//						   }
//						   ],
//		"attachFiles": [
//						{
//							"documentId": 382752,
//							"attachment": "/Van_ban/2012/7/26/382752/SEFOLTgwMDI4NTIyOTAwMDAtMDlDTi1ZMjAxMS1MMDAgQkg=.pdf",
//							"name": "HAN-8002852290000-09CN-Y2011-L00 BH.pdf",
//							"fileAttachmentId": 373056
//						}
//						],
//		"listComment": [
//						{
//							"staffId": 55433,
//							"receiverId": 26201,
//							"receiveDate": "31/05/2016 09:52:57",
//							"commentContent": "New",
//							"groupId": 6683,
//							"senderName": "Nguyen Thanh Nam",
//							"fullName": "Nguyen Thanh Nam",
//							"senderEmail": "abcd@viettel.com.vn",
//							"senderMobile": "132435345",
//							"senderGroupName": "Tổng Công ty Mạng lưới Viettel fullnameVO1",
//							"groupName": "Tổng Công ty Mạng lưới Viettel fullnameVO1",
//							"receiverName": "Nguyễn Phúc Đức",
//							"receiverEmail": "email010993@viettel.com.vn",
//							"isReceiveDirect": true
//						},
//						{
//							"staffId": 55433,
//							"receiverId": 26201,
//							"receiveDate": "31/05/2016 09:52:57",
//							"commentContent": "New",
//							"groupId": 6683,
//							"senderName": "Nguyen Thanh Nam",
//							"fullName": "Nguyen Thanh Nam",
//							"senderEmail": "abcd@viettel.com.vn",
//							"senderMobile": "132435345",
//							"senderGroupName": "Tổng Công ty Mạng lưới Viettel fullnameVO1",
//							"groupName": "Tổng Công ty Mạng lưới Viettel fullnameVO1",
//							"receiverName": "Nguyễn Phúc Đức",
//							"receiverEmail": "email010993@viettel.com.vn",
//							"isReceiveDirect": true
//						},
//						{
//							"staffId": 72,
//							"receiverId": 26201,
//							"receiveDate": "26/05/2016 18:20:40",
//							"commentContent": "test",
//							"groupId": 38,
//							"staffId2": 495224,
//							"groupId2": 254951,
//							"receiverId2": 1054,
//							"senderName": "Phạm Thị Hạnh",
//							"fullName": "Phạm Thị Hạnh",
//							"senderEmail": "495224",
//							"senderMobile": "0976636353",
//							"senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							"groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							"receiverName": "Nguyễn Thanh Nam",
//							"receiverEmail": "1054",
//							"isReceiveDirect": true
//						},
//						{
//							"staffId": 72,
//							"receiverId": 55433,
//							"receiveDate": "26/05/2016 18:29:08",
//							"commentContent": "test",
//							"groupId": 38,
//							"staffId2": 495224,
//							"groupId2": 254951,
//							"receiverId2": 1054,
//							"senderName": "Phạm Thị Hạnh",
//							"fullName": "Phạm Thị Hạnh",
//							"senderEmail": "495224",
//							"senderMobile": "0976636353",
//							"senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							"groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							"receiverName": "Nguyễn Thanh Nam",
//							"receiverEmail": "1054",
//							"dReceiveDate": "May 26, 2016 6:29:08 PM"
//						},
//						{
//							"staffId": 72,
//							"receiverId": 55433,
//							"receiveDate": "26/05/2016 18:29:08",
//							"commentContent": "test",
//							"groupId": 38,
//							"staffId2": 495224,
//							"groupId2": 254951,
//							"receiverId2": 1054,
//							"senderName": "Phạm Thị Hạnh",
//							"fullName": "Phạm Thị Hạnh",
//							"senderEmail": "495224",
//							"senderMobile": "0976636353",
//							"senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							"groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							"receiverName": "Nguyễn Thanh Nam",
//							"receiverEmail": "1054",
//							"dReceiveDate": "May 26, 2016 6:29:08 PM"
//						},
//						{
//							"staffId": 72,
//							"receiverId": 55433,
//							"receiveDate": "26/05/2016 18:26:48",
//							"commentContent": "test",
//							"groupId": 38,
//							"staffId2": 495224,
//							"groupId2": 254951,
//							"receiverId2": 1054,
//							"senderName": "Phạm Thị Hạnh",
//							"fullName": "Phạm Thị Hạnh",
//							"senderEmail": "495224",
//							"senderMobile": "0976636353",
//							"senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							"groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							"receiverName": "Nguyễn Thanh Nam",
//							"receiverEmail": "1054",
//							"dReceiveDate": "May 26, 2016 6:26:48 PM"
//						},
//						{
//							"staffId": 72,
//							"receiverId": 55433,
//							"receiveDate": "26/05/2016 18:26:48",
//							"commentContent": "test",
//							"groupId": 38,
//							"staffId2": 495224,
//							"groupId2": 254951,
//							"receiverId2": 1054,
//							"senderName": "Phạm Thị Hạnh",
//							"fullName": "Phạm Thị Hạnh",
//							"senderEmail": "495224",
//							"senderMobile": "0976636353",
//							"senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							"groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							"receiverName": "Nguyễn Thanh Nam",
//							"receiverEmail": "1054",
//							"dReceiveDate": "May 26, 2016 6:26:48 PM"
//						},
//						{
//							"staffId": 72,
//							"receiverId": 55433,
//							"receiveDate": "26/05/2016 18:26:03",
//							"commentContent": "test",
//							"groupId": 38,
//							"staffId2": 495224,
//							"groupId2": 254951,
//							"receiverId2": 1054,
//							"senderName": "Phạm Thị Hạnh",
//							"fullName": "Phạm Thị Hạnh",
//							"senderEmail": "495224",
//							"senderMobile": "0976636353",
//							"senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							"groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							"receiverName": "Nguyễn Thanh Nam",
//							"receiverEmail": "1054",
//							"dReceiveDate": "May 26, 2016 6:26:03 PM"
//						},
//						{
//							"staffId": 72,
//							"receiverId": 55433,
//							"receiveDate": "26/05/2016 18:26:03",
//							"commentContent": "test",
//							"groupId": 38,
//							"staffId2": 495224,
//							"groupId2": 254951,
//							"receiverId2": 1054,
//							"senderName": "Phạm Thị Hạnh",
//							"fullName": "Phạm Thị Hạnh",
//							"senderEmail": "495224",
//							"senderMobile": "0976636353",
//							"senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							"groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							"receiverName": "Nguyễn Thanh Nam",
//							"receiverEmail": "1054",
//							"dReceiveDate": "May 26, 2016 6:26:03 PM"
//						},
//						{
//							"staffId": 72,
//							"receiverId": 55433,
//							"receiveDate": "26/05/2016 18:17:41",
//							"commentContent": "test",
//							"groupId": 38,
//							"staffId2": 495224,
//							"groupId2": 254951,
//							"receiverId2": 1054,
//							"senderName": "Phạm Thị Hạnh",
//							"fullName": "Phạm Thị Hạnh",
//							"senderEmail": "495224",
//							"senderMobile": "0976636353",
//							"senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							"groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							"receiverName": "Nguyễn Thanh Nam",
//							"receiverEmail": "1054",
//							"dReceiveDate": "May 26, 2016 6:17:41 PM"
//						},
//						{
//							"staffId": 72,
//							"receiverId": 55433,
//							"receiveDate": "26/05/2016 18:17:41",
//							"commentContent": "test",
//							"groupId": 38,
//							"staffId2": 495224,
//							"groupId2": 254951,
//							"receiverId2": 1054,
//							"senderName": "Phạm Thị Hạnh",
//							"fullName": "Phạm Thị Hạnh",
//							"senderEmail": "495224",
//							"senderMobile": "0976636353",
//							"senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							"groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							"receiverName": "Nguyễn Thanh Nam",
//							"receiverEmail": "1054",
//							"dReceiveDate": "May 26, 2016 6:17:41 PM"
//						}
//						],
//		"listReceiverSameUser": [],
//		"listReceiver": [
//						 {
//							 "staffId": 26201,
//							 "receiverId": 42789,
//							 "receiveDate": "30/05/2016 09:06:33",
//							 "commentContent": "test",
//							 "receiverGroupId": 0,
//							 "staffId2": 6485,
//							 "receiverId2": 733,
//							 "receiverGroupId2": 148845,
//							 "fullName": "Hoàng Anh Xuân",
//							 "groupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//							 "receiverName": "Hoàng Anh Xuân",
//							 "receiverEmail": "733",
//							 "receiverMobile": "0000000000",
//							 "receiverGroupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//							 "email": "733",
//							 "mobile": "0000000000",
//							 "total": 27,
//							 "status": 2,
//							 "documentInStaffId": 28061911,
//							 "isProcessed": 0,
//							 "isInDepartment": 0
//						 },
//						 {
//							 "staffId": 26201,
//							 "receiverId": 55377,
//							 "receiveDate": "30/05/2016 09:06:33",
//							 "commentContent": "test",
//							 "receiverGroupId": 0,
//							 "staffId2": 6485,
//							 "receiverId2": 736,
//							 "receiverGroupId2": 148845,
//							 "fullName": "Lê Đăng Dũng",
//							 "groupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//							 "receiverName": "Lê Đăng Dũng",
//							 "receiverEmail": "736",
//							 "receiverMobile": "0000000000",
//							 "receiverGroupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//							 "email": "736",
//							 "mobile": "0000000000",
//							 "status": 2,
//							 "documentInStaffId": 28061912,
//							 "isProcessed": 0,
//							 "isInDepartment": 0
//						 },
//						 {
//							 "staffId": 26201,
//							 "receiverId": 55378,
//							 "receiveDate": "30/05/2016 09:06:33",
//							 "commentContent": "test",
//							 "receiverGroupId": 0,
//							 "staffId2": 6485,
//							 "receiverId2": 2440,
//							 "receiverGroupId2": 148845,
//							 "fullName": "Hoàng Công Vĩnh",
//							 "groupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//							 "receiverName": "Hoàng Công Vĩnh",
//							 "receiverEmail": "2440",
//							 "receiverMobile": "0000000000",
//							 "receiverGroupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//							 "email": "2440",
//							 "mobile": "0000000000",
//							 "status": 2,
//							 "documentInStaffId": 28061916,
//							 "isProcessed": 0,
//							 "isInDepartment": 0
//						 },
//						 {
//							 "staffId": 26201,
//							 "receiverId": 25,
//							 "receiveDate": "30/05/2016 09:06:33",
//							 "commentContent": "test",
//							 "receiverGroupId": 0,
//							 "staffId2": 6485,
//							 "receiverId2": 8840,
//							 "receiverGroupId2": 148845,
//							 "fullName": "Hoàng Sơn",
//							 "groupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//							 "receiverName": "Hoàng Sơn",
//							 "receiverEmail": "8840",
//							 "receiverMobile": "0000000000",
//							 "receiverGroupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//							 "email": "8840",
//							 "mobile": "0000000000",
//							 "status": 2,
//							 "documentInStaffId": 28061904,
//							 "isProcessed": 0,
//							 "isInDepartment": 0
//						 },
//						 {
//							 "staffId": 26201,
//							 "receiverId": 52026,
//							 "receiveDate": "30/05/2016 09:06:33",
//							 "commentContent": "test",
//							 "receiverGroupId": 0,
//							 "staffId2": 6485,
//							 "receiverId2": 737,
//							 "receiverGroupId2": 148845,
//							 "fullName": "Nguyễn Mạnh Hùng",
//							 "groupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//							 "receiverName": "Nguyễn Mạnh Hùng",
//							 "receiverEmail": "737",
//							 "receiverMobile": "0000000000",
//							 "receiverGroupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//							 "email": "737",
//							 "mobile": "0000000000",
//							 "status": 2,
//							 "documentInStaffId": 28061903,
//							 "isProcessed": 0,
//							 "isInDepartment": 0
//						 }
//						 ],
//		"listGroup": [
//					  {
//						  "receiverGroupId": 78,
//						  "staffId": 26201,
//						  "groupId": 6683,
//						  "receiveDate": "24/05/2016 14:12:17",
//						  "documentInGroupId": 5082,
//						  "documentId": 382752,
//						  "receiverGroupName": "Phòng Kỹ thuật",
//						  "receiverParentGroupId": 6683,
//						  "groupName": "Phòng Kỹ thuật",
//						  "total": 5
//					  },
//					  {
//						  "receiverGroupId": 6697,
//						  "staffId": 26201,
//						  "groupId": 6683,
//						  "receiveDate": "24/05/2016 14:12:17",
//						  "documentInGroupId": 5081,
//						  "documentId": 382752,
//						  "receiverGroupName": "Phòng Kế hoạch ",
//						  "receiverParentGroupId": 6683,
//						  "groupName": "Phòng Kế hoạch ",
//						  "total": 0
//					  },
//					  {
//						  "receiverGroupId": 135154,
//						  "staffId": 26201,
//						  "groupId": 6683,
//						  "receiveDate": "24/05/2016 14:12:17",
//						  "documentInGroupId": 5080,
//						  "documentId": 382752,
//						  "receiverGroupName": "Phòng Công nghệ Thông tin",
//						  "receiverParentGroupId": 6683,
//						  "groupName": "Phòng Công nghệ Thông tin",
//						  "total": 0
//					  },
//					  {
//						  "receiverGroupId": 6701,
//						  "staffId": 26201,
//						  "groupId": 6683,
//						  "receiveDate": "24/05/2016 14:12:16",
//						  "documentInGroupId": 5079,
//						  "documentId": 382752,
//						  "receiverGroupName": "Phòng Chính trị",
//						  "receiverParentGroupId": 6683,
//						  "groupName": "Phòng Chính trị",
//						  "total": 0
//					  },
//					  {
//						  "receiverGroupId": 118007,
//						  "staffId": 26201,
//						  "groupId": 6683,
//						  "receiveDate": "24/05/2016 14:12:16",
//						  "documentInGroupId": 5078,
//						  "documentId": 382752,
//						  "receiverGroupName": "Ban Truyền thông",
//						  "receiverParentGroupId": 6683,
//						  "groupName": "Ban Truyền thông",
//						  "total": 0
//					  }
//					  ],
//		"id": 382752,
//		"isConfidential": 1,
//		"toDate": "26/07/2012 00:00:00",
//		"documentAdjacentTypeId": 1,
//		"commentFromDir": [
//						   {
//							   "staffId": 55433,
//							   "receiverId": 26201,
//							   "receiveDate": "31/05/2016 09:52:57",
//							   "commentContent": "New",
//							   "groupId": 6683,
//							   "senderName": "Nguyen Thanh Nam",
//							   "fullName": "Nguyen Thanh Nam",
//							   "senderEmail": "abcd@viettel.com.vn",
//							   "senderMobile": "132435345",
//							   "senderGroupName": "Tổng Công ty Mạng lưới Viettel fullnameVO1",
//							   "groupName": "Tổng Công ty Mạng lưới Viettel fullnameVO1",
//							   "receiverName": "Nguyễn Phúc Đức",
//							   "receiverEmail": "email010993@viettel.com.vn",
//							   "isReceiveDirect": true
//						   },
//						   {
//							   "staffId": 55433,
//							   "receiverId": 26201,
//							   "receiveDate": "31/05/2016 09:52:57",
//							   "commentContent": "New",
//							   "groupId": 6683,
//							   "senderName": "Nguyen Thanh Nam",
//							   "fullName": "Nguyen Thanh Nam",
//							   "senderEmail": "abcd@viettel.com.vn",
//							   "senderMobile": "132435345",
//							   "senderGroupName": "Tổng Công ty Mạng lưới Viettel fullnameVO1",
//							   "groupName": "Tổng Công ty Mạng lưới Viettel fullnameVO1",
//							   "receiverName": "Nguyễn Phúc Đức",
//							   "receiverEmail": "email010993@viettel.com.vn",
//							   "isReceiveDirect": true
//						   },
//						   {
//							   "staffId": 72,
//							   "receiverId": 26201,
//							   "receiveDate": "26/05/2016 18:20:40",
//							   "commentContent": "test",
//							   "groupId": 38,
//							   "staffId2": 495224,
//							   "groupId2": 254951,
//							   "receiverId2": 1054,
//							   "senderName": "Phạm Thị Hạnh",
//							   "fullName": "Phạm Thị Hạnh",
//							   "senderEmail": "495224",
//							   "senderMobile": "0976636353",
//							   "senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							   "groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							   "receiverName": "Nguyễn Thanh Nam",
//							   "receiverEmail": "1054",
//							   "isReceiveDirect": true
//						   },
//						   {
//							   "staffId": 72,
//							   "receiverId": 55433,
//							   "receiveDate": "26/05/2016 18:29:08",
//							   "commentContent": "test",
//							   "groupId": 38,
//							   "staffId2": 495224,
//							   "groupId2": 254951,
//							   "receiverId2": 1054,
//							   "senderName": "Phạm Thị Hạnh",
//							   "fullName": "Phạm Thị Hạnh",
//							   "senderEmail": "495224",
//							   "senderMobile": "0976636353",
//							   "senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							   "groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							   "receiverName": "Nguyễn Thanh Nam",
//							   "receiverEmail": "1054",
//							   "dReceiveDate": "May 26, 2016 6:29:08 PM"
//						   },
//						   {
//							   "staffId": 72,
//							   "receiverId": 55433,
//							   "receiveDate": "26/05/2016 18:29:08",
//							   "commentContent": "test",
//							   "groupId": 38,
//							   "staffId2": 495224,
//							   "groupId2": 254951,
//							   "receiverId2": 1054,
//							   "senderName": "Phạm Thị Hạnh",
//							   "fullName": "Phạm Thị Hạnh",
//							   "senderEmail": "495224",
//							   "senderMobile": "0976636353",
//							   "senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							   "groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							   "receiverName": "Nguyễn Thanh Nam",
//							   "receiverEmail": "1054",
//							   "dReceiveDate": "May 26, 2016 6:29:08 PM"
//						   },
//						   {
//							   "staffId": 72,
//							   "receiverId": 55433,
//							   "receiveDate": "26/05/2016 18:26:48",
//							   "commentContent": "test",
//							   "groupId": 38,
//							   "staffId2": 495224,
//							   "groupId2": 254951,
//							   "receiverId2": 1054,
//							   "senderName": "Phạm Thị Hạnh",
//							   "fullName": "Phạm Thị Hạnh",
//							   "senderEmail": "495224",
//							   "senderMobile": "0976636353",
//							   "senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							   "groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							   "receiverName": "Nguyễn Thanh Nam",
//							   "receiverEmail": "1054",
//							   "dReceiveDate": "May 26, 2016 6:26:48 PM"
//						   },
//						   {
//							   "staffId": 72,
//							   "receiverId": 55433,
//							   "receiveDate": "26/05/2016 18:26:48",
//							   "commentContent": "test",
//							   "groupId": 38,
//							   "staffId2": 495224,
//							   "groupId2": 254951,
//							   "receiverId2": 1054,
//							   "senderName": "Phạm Thị Hạnh",
//							   "fullName": "Phạm Thị Hạnh",
//							   "senderEmail": "495224",
//							   "senderMobile": "0976636353",
//							   "senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							   "groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							   "receiverName": "Nguyễn Thanh Nam",
//							   "receiverEmail": "1054",
//							   "dReceiveDate": "May 26, 2016 6:26:48 PM"
//						   },
//						   {
//							   "staffId": 72,
//							   "receiverId": 55433,
//							   "receiveDate": "26/05/2016 18:26:03",
//							   "commentContent": "test",
//							   "groupId": 38,
//							   "staffId2": 495224,
//							   "groupId2": 254951,
//							   "receiverId2": 1054,
//							   "senderName": "Phạm Thị Hạnh",
//							   "fullName": "Phạm Thị Hạnh",
//							   "senderEmail": "495224",
//							   "senderMobile": "0976636353",
//							   "senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							   "groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							   "receiverName": "Nguyễn Thanh Nam",
//							   "receiverEmail": "1054",
//							   "dReceiveDate": "May 26, 2016 6:26:03 PM"
//						   },
//						   {
//							   "staffId": 72,
//							   "receiverId": 55433,
//							   "receiveDate": "26/05/2016 18:26:03",
//							   "commentContent": "test",
//							   "groupId": 38,
//							   "staffId2": 495224,
//							   "groupId2": 254951,
//							   "receiverId2": 1054,
//							   "senderName": "Phạm Thị Hạnh",
//							   "fullName": "Phạm Thị Hạnh",
//							   "senderEmail": "495224",
//							   "senderMobile": "0976636353",
//							   "senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							   "groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							   "receiverName": "Nguyễn Thanh Nam",
//							   "receiverEmail": "1054",
//							   "dReceiveDate": "May 26, 2016 6:26:03 PM"
//						   },
//						   {
//							   "staffId": 72,
//							   "receiverId": 55433,
//							   "receiveDate": "26/05/2016 18:17:41",
//							   "commentContent": "test",
//							   "groupId": 38,
//							   "staffId2": 495224,
//							   "groupId2": 254951,
//							   "receiverId2": 1054,
//							   "senderName": "Phạm Thị Hạnh",
//							   "fullName": "Phạm Thị Hạnh",
//							   "senderEmail": "495224",
//							   "senderMobile": "0976636353",
//							   "senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							   "groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							   "receiverName": "Nguyễn Thanh Nam",
//							   "receiverEmail": "1054",
//							   "dReceiveDate": "May 26, 2016 6:17:41 PM"
//						   },
//						   {
//							   "staffId": 72,
//							   "receiverId": 55433,
//							   "receiveDate": "26/05/2016 18:17:41",
//							   "commentContent": "test",
//							   "groupId": 38,
//							   "staffId2": 495224,
//							   "groupId2": 254951,
//							   "receiverId2": 1054,
//							   "senderName": "Phạm Thị Hạnh",
//							   "fullName": "Phạm Thị Hạnh",
//							   "senderEmail": "495224",
//							   "senderMobile": "0976636353",
//							   "senderGroupName": "Phòng Sản phẩm văn phòng điện tử",
//							   "groupName": "Phòng Sản phẩm văn phòng điện tử - Trung tâm Phần mềm Viettel 1",
//							   "receiverName": "Nguyễn Thanh Nam",
//							   "receiverEmail": "1054",
//							   "dReceiveDate": "May 26, 2016 6:17:41 PM"
//						   }
//						   ],
//		"empRecipientDoc": [],
//		"empSendDoc": [
//					   {
//						   "staffId": 26201,
//						   "receiverId": 42789,
//						   "receiveDate": "30/05/2016 09:06:33",
//						   "commentContent": "test",
//						   "receiverGroupId": 0,
//						   "staffId2": 6485,
//						   "receiverId2": 733,
//						   "receiverGroupId2": 148845,
//						   "fullName": "Hoàng Anh Xuân",
//						   "groupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//						   "receiverName": "Hoàng Anh Xuân",
//						   "receiverEmail": "733",
//						   "receiverMobile": "0000000000",
//						   "receiverGroupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//						   "email": "733",
//						   "mobile": "0000000000",
//						   "total": 27,
//						   "status": 2,
//						   "documentInStaffId": 28061911,
//						   "isProcessed": 0,
//						   "isInDepartment": 0
//					   },
//					   {
//						   "staffId": 26201,
//						   "receiverId": 55377,
//						   "receiveDate": "30/05/2016 09:06:33",
//						   "commentContent": "test",
//						   "receiverGroupId": 0,
//						   "staffId2": 6485,
//						   "receiverId2": 736,
//						   "receiverGroupId2": 148845,
//						   "fullName": "Lê Đăng Dũng",
//						   "groupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//						   "receiverName": "Lê Đăng Dũng",
//						   "receiverEmail": "736",
//						   "receiverMobile": "0000000000",
//						   "receiverGroupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//						   "email": "736",
//						   "mobile": "0000000000",
//						   "status": 2,
//						   "documentInStaffId": 28061912,
//						   "isProcessed": 0,
//						   "isInDepartment": 0
//					   },
//					   {
//						   "staffId": 26201,
//						   "receiverId": 55378,
//						   "receiveDate": "30/05/2016 09:06:33",
//						   "commentContent": "test",
//						   "receiverGroupId": 0,
//						   "staffId2": 6485,
//						   "receiverId2": 2440,
//						   "receiverGroupId2": 148845,
//						   "fullName": "Hoàng Công Vĩnh",
//						   "groupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//						   "receiverName": "Hoàng Công Vĩnh",
//						   "receiverEmail": "2440",
//						   "receiverMobile": "0000000000",
//						   "receiverGroupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//						   "email": "2440",
//						   "mobile": "0000000000",
//						   "status": 2,
//						   "documentInStaffId": 28061916,
//						   "isProcessed": 0,
//						   "isInDepartment": 0
//					   },
//					   {
//						   "staffId": 26201,
//						   "receiverId": 25,
//						   "receiveDate": "30/05/2016 09:06:33",
//						   "commentContent": "test",
//						   "receiverGroupId": 0,
//						   "staffId2": 6485,
//						   "receiverId2": 8840,
//						   "receiverGroupId2": 148845,
//						   "fullName": "Hoàng Sơn",
//						   "groupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//						   "receiverName": "Hoàng Sơn",
//						   "receiverEmail": "8840",
//						   "receiverMobile": "0000000000",
//						   "receiverGroupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//						   "email": "8840",
//						   "mobile": "0000000000",
//						   "status": 2,
//						   "documentInStaffId": 28061904,
//						   "isProcessed": 0,
//						   "isInDepartment": 0
//					   },
//					   {
//						   "staffId": 26201,
//						   "receiverId": 52026,
//						   "receiveDate": "30/05/2016 09:06:33",
//						   "commentContent": "test",
//						   "receiverGroupId": 0,
//						   "staffId2": 6485,
//						   "receiverId2": 737,
//						   "receiverGroupId2": 148845,
//						   "fullName": "Nguyễn Mạnh Hùng",
//						   "groupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//						   "receiverName": "Nguyễn Mạnh Hùng",
//						   "receiverEmail": "737",
//						   "receiverMobile": "0000000000",
//						   "receiverGroupName": "Thủ trưởng đơn vị - Ban Giám đốc Tập đoàn - Khối cơ quan Tập đoàn",
//						   "email": "737",
//						   "mobile": "0000000000",
//						   "status": 2,
//						   "documentInStaffId": 28061903,
//						   "isProcessed": 0,
//						   "isInDepartment": 0
//					   }
//        ],
//		"groupReceiverDoc": [
//							 {
//								 "receiverGroupId": 78,
//								 "staffId": 26201,
//								 "groupId": 6683,
//								 "receiveDate": "24/05/2016 14:12:17",
//								 "documentInGroupId": 5082,
//								 "documentId": 382752,
//								 "receiverGroupName": "Phòng Kỹ thuật",
//								 "receiverParentGroupId": 6683,
//								 "groupName": "Phòng Kỹ thuật",
//								 "total": 5
//							 },
//							 {
//								 "receiverGroupId": 6697,
//								 "staffId": 26201,
//								 "groupId": 6683,
//								 "receiveDate": "24/05/2016 14:12:17",
//								 "documentInGroupId": 5081,
//								 "documentId": 382752,
//								 "receiverGroupName": "Phòng Kế hoạch ",
//								 "receiverParentGroupId": 6683,
//								 "groupName": "Phòng Kế hoạch ",
//								 "total": 0
//							 },
//							 {
//								 "receiverGroupId": 135154,
//								 "staffId": 26201,
//								 "groupId": 6683,
//								 "receiveDate": "24/05/2016 14:12:17",
//								 "documentInGroupId": 5080,
//								 "documentId": 382752,
//								 "receiverGroupName": "Phòng Công nghệ Thông tin",
//								 "receiverParentGroupId": 6683,
//								 "groupName": "Phòng Công nghệ Thông tin",
//								 "total": 0
//							 },
//							 {
//								 "receiverGroupId": 6701,
//								 "staffId": 26201,
//								 "groupId": 6683,
//								 "receiveDate": "24/05/2016 14:12:16",
//								 "documentInGroupId": 5079,
//								 "documentId": 382752,
//								 "receiverGroupName": "Phòng Chính trị",
//								 "receiverParentGroupId": 6683,
//								 "groupName": "Phòng Chính trị",
//								 "total": 0
//							 },
//							 {
//								 "receiverGroupId": 118007,
//								 "staffId": 26201,
//								 "groupId": 6683,
//								 "receiveDate": "24/05/2016 14:12:16",
//								 "documentInGroupId": 5078,
//								 "documentId": 382752,
//								 "receiverGroupName": "Ban Truyền thông",
//								 "receiverParentGroupId": 6683,
//								 "groupName": "Ban Truyền thông",
//								 "total": 0
//							 }
//        ],
//		"lstCvGroup": [
//					   {
//						   "groupID": 2323,
//						   "groupId": 2323,
//						   "name": " Trưởng phó P/B thuộc TTKV3",
//						   "receiveDate": "28/05/2016 09:29:50"
//					   },
//					   {
//						   "groupID": 10375,
//						   "groupId": 10375,
//						   "name": "646464",
//						   "receiveDate": "28/05/2016 09:29:50"
//					   }
//        ],
//		"sendDocType": "Gửi qua hệ thống Voffice"
//	},
//	"resultCode": 200
//}
